version: "3.8"

services:
  # ----------------------------------------
  # Dịch vụ MySQL Database
  # ----------------------------------------
  mysql:
    image: mysql:8.0.36
    container_name: mysql-sachcu
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: sachcu_db
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--skip-character-set-client-handshake",
      ]
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "3306:3306"
    networks:
      - app-network

  # ----------------------------------------
  # Dịch vụ Adminer (Giao diện quản lý DB)
  # ----------------------------------------
  adminer:
    image: adminer
    container_name: adminer-sachcu
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    networks:
      - app-network

# ----------------------------------------
# Định nghĩa Volumes và Networks
# ----------------------------------------

volumes:
  mysql_data:

networks:
  app-network:
